wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "wiki"
urlpatterns = [
    path("", views.index, name="index"),
    path("newpage", views.newpage, name="newpage"),
    path("editpage/<str:title>", views.editpage, name="editpage"),
    path("randompage", views.randompage, name="randompage"),
    path("search", views.search, name="search"),
    path("<str:title>", views.title, name="title"),




]

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('wiki/', include("encyclopedia.urls"))
]

wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/encyclopedia/views.py
from markdown2 import Markdown
from django.shortcuts import render, redirect
from django import forms
from django.http import HttpResponseRedirect
from django.urls import reverse
import random

from . import util

class NewPageForm(forms.Form):
    title = forms.CharField(label="Title")
    text = forms.CharField(widget=forms.Textarea(), label="Text")

class EditPageForm(forms.Form):
    text = forms.CharField(widget=forms.Textarea(), label="Text")

def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })


def title(request, title):
    content_md = util.get_entry(title)
    if content_md is not None:
        content_html = Markdown().convert(content_md)
        return render(request, "encyclopedia/title.html", {
         "content": content_html,
         "title": title.capitalize()
        })
    else:
        return render(request, "encyclopedia/error.html", {
        "title": title.capitalize()
        })


def search(request):
    if request.method == "GET":
        q = request.GET["q"]
        q_low = q.lower()

        if q_low in (q.lower() for q in util.list_entries()):
            return redirect("wiki:title", q)
        else:
            search = [i for i in util.list_entries() if q_low in i.lower()]
            return render(request, "encyclopedia/search.html", {
            "entries": search
        })

def newpage(request):
    if request.method == "POST":
        form = NewPageForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            text = form.cleaned_data["text"]
            if title.lower() not in (i.lower() for i in util.list_entries()):
                util.save_entry(title, text)
                return redirect("wiki:title", title)
            else:
                return render(request, "encyclopedia/error2.html", {
                "title": title.capitalize()
                })
        else:
            return render(request, "encyclopedia/newpage.html", {
            "form": form
            })
    return render(request, "encyclopedia/newpage.html", {
        "form": NewPageForm()
    })

def editpage(request, title):
    if request.method == "POST":
        form = EditPageForm(request.POST)
        if form.is_valid():
            text = form.cleaned_data["text"]
            util.save_entry(title, text)
            return redirect("wiki:title", title)
        else:
            text = util.get_entry(title)
            return render(request, "encyclopedia/editpage.html", {
            "title": title,
            "form": EditPageForm(initial={'text':text})
            })

    else:
        text = util.get_entry(title)
        return render(request, "encyclopedia/editpage.html", {
        "title": title,
        "form": EditPageForm(initial={'text':text})
        })

def randompage(request):
        title = random.choice(util.list_entries())
        return redirect("wiki:title", title)
    

wiki/encyclopedia/templates/encyclopedia/editpage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
<h1>Edit Page {{title}}</h1>
 <form action="{% url 'wiki:editpage' title=title%}" method="post">
   {%csrf_token%}
   <table>
   {{form.as_table}}
   </table>

   <input type="submit", value=Submit>
 </form>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
{{title}}
{% endblock %}

{% block body %}

Page was not found

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/error2.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
{{title}}
{% endblock %}

{% block body %}

Entry {{title}} already exists

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li>
            <a href="{% url 'wiki:title' title=entry %}">{{ entry }}</a>
            </li>
        {% endfor %}
    </ul>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'wiki:search' %}" method="get">
                    {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">

                </form>
                <div>
                    <a href="{% url 'wiki:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'wiki:newpage' %}"> Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'wiki:randompage'%}"> Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

wiki/encyclopedia/templates/encyclopedia/newpage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
<h1>Create New Page</h1>
 <form action="{% url 'wiki:newpage'%}" method="post">
   {%csrf_token%}
   <table>
   {{form.as_table}}
   </table>

   <input type="submit", value=Submit>
 </form>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Not found</h1>
    The requested entry was not found. Did you mean:
    <ul>
        {% for entry in entries %}
            <li>
            <a href="{% url 'wiki:title' title=entry %}">{{ entry }}</a>
            </li>
        {% endfor %}
    </ul>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/title.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
{{title}}
{% endblock %}

{% block body %}
    {{content|safe}}

<a href="{% url 'wiki:editpage' title=title%}">Edit Page</a>
{% endblock %}